return {
	-- "nvim-lualine/lualine.nvim",
	-- 		options = {
	-- 			theme = "catpuccin-frappe",
	-- 			section_separators = { left = "", right = "" },
	-- 			component_separators = { left = "", right = "" },
	-- 		},
	-- 		sections = {
	-- 			lualine_a = { "mode" },
	-- 			lualine_b = { "branch" },
	-- 			lualine_c = {
	-- 				{
	-- 					"macro",
	-- 					fmt = function()
	-- 						local reg = vim.fn.reg_recording()
	-- 						if reg ~= "" then
	-- 							return"Recording @" .. reg
	-- 					end,
	-- 					color = { fg = "#ff9e64" },
	-- 					draw_empty = false,
	-- 				},
	-- 				{ "filename", path = 1 },
	-- 			},
	--
	-- 			lualine_x = {
	-- 				"filetype",
	-- 			},
	-- 			lualine_y = { "progress" },
	-- 			lualine_z = { "location" },
	-- 		},
	-- 	})
	-- end,
}
